type RedditVideo = {
  bitrate_kbps: number;
  fallback_url: string;
  height: number;
  width: number;
  scrubber_media_url: string;
  dash_url: string;
  duration: number;
  hls_url: string;
  is_gif: boolean;
  transcoding_status: string;
};

type SecureMedia = {
  reddit_video: RedditVideo;
};

type Source = {
  url: string;
  width: number;
  height: number;
};

type Resolution = {
  url: string;
  width: number;
  height: number;
};

type Image = {
  source: Source;
  resolutions: Resolution[];
  variants: null;
  id: string;
};

type Preview = {
  images: Image[];
  enabled: boolean;
};

type ResizedIcon = {
  url: string;
  width: number;
  height: number;
};

type ResizedStaticIcon = {
  url: string;
  width: number;
  height: number;
};

type AllAwarding = {
  giver_coin_reward?: any;
  subreddit_id?: any;
  is_new: boolean;
  days_of_drip_extension?: any;
  coin_price: number;
  id: string;
  penny_donate?: any;
  award_sub_type: string;
  coin_reward: number;
  icon_url: string;
  days_of_premium?: any;
  tiers_by_required_awardings?: any;
  resized_icons: ResizedIcon[];
  icon_width: number;
  static_icon_width: number;
  start_date?: any;
  is_enabled: boolean;
  awardings_required_to_grant_benefits?: any;
  description: string;
  end_date?: any;
  subreddit_coin_reward: number;
  count: number;
  static_icon_height: number;
  name: string;
  resized_static_icons: ResizedStaticIcon[];
  icon_format?: any;
  icon_height: number;
  penny_price?: any;
  award_type: string;
  static_icon_url: string;
};

type Media = {
  reddit_video: RedditVideo;
};

type CrosspostParentList = {
  approved_at_utc?: any;
  subreddit: string;
  selftext: string;
  author_fullname: string;
  saved: boolean;
  mod_reason_title?: any;
  gilded: number;
  clicked: boolean;
  title: string;
  link_flair_richtext: any[];
  subreddit_name_prefixed: string;
  hidden: boolean;
  pwls: number;
  link_flair_css_class: string;
  downs: number;
  thumbnail_height: number;
  top_awarded_type?: any;
  hide_score: boolean;
  name: string;
  quarantine: boolean;
  link_flair_text_color: string;
  upvote_ratio: number;
  author_flair_background_color: string;
  ups: number;
  total_awards_received: number;
  media_embed: null;
  thumbnail_width: number;
  author_flair_template_id?: any;
  is_original_content: boolean;
  user_reports: any[];
  secure_media?: any;
  is_reddit_media_domain: boolean;
  is_meta: boolean;
  category?: any;
  secure_media_embed: null;
  link_flair_text: string;
  can_mod_post: boolean;
  score: number;
  approved_by?: any;
  is_created_from_ads_ui: boolean;
  author_premium: boolean;
  thumbnail: string;
  edited: boolean;
  author_flair_css_class?: any;
  author_flair_richtext: any[];
  gildings: null;
  post_hint: string;
  content_categories?: any;
  is_self: boolean;
  subreddit_type: string;
  created: number;
  link_flair_type: string;
  wls: number;
  removed_by_category?: any;
  banned_by?: any;
  author_flair_type: string;
  domain: string;
  allow_live_comments: boolean;
  selftext_html?: any;
  likes?: any;
  suggested_sort?: any;
  banned_at_utc?: any;
  url_overridden_by_dest: string;
  view_count?: any;
  archived: boolean;
  no_follow: boolean;
  is_crosspostable: boolean;
  pinned: boolean;
  over_18: boolean;
  preview: Preview;
  all_awardings: any[];
  awarders: any[];
  media_only: boolean;
  link_flair_template_id: string;
  can_gild: boolean;
  spoiler: boolean;
  locked: boolean;
  author_flair_text: string;
  treatment_tags: any[];
  visited: boolean;
  removed_by?: any;
  mod_note?: any;
  distinguished?: any;
  subreddit_id: string;
  author_is_blocked: boolean;
  mod_reason_by?: any;
  num_reports?: any;
  removal_reason?: any;
  link_flair_background_color: string;
  id: string;
  is_robot_indexable: boolean;
  report_reasons?: any;
  author: string;
  discussion_type?: any;
  num_comments: number;
  send_replies: boolean;
  whitelist_status: string;
  contest_mode: boolean;
  mod_reports: any[];
  author_patreon_flair: boolean;
  author_flair_text_color: string;
  permalink: string;
  parent_whitelist_status: string;
  stickied: boolean;
  url: string;
  subreddit_subscribers: number;
  created_utc: number;
  num_crossposts: number;
  media?: any;
  is_video: boolean;
};

export type PostData = {
  approved_at_utc?: any;
  subreddit: string;
  selftext: string;
  author_fullname: string;
  saved: boolean;
  mod_reason_title?: any;
  gilded: number;
  clicked: boolean;
  title: string;
  link_flair_richtext: any[];
  subreddit_name_prefixed: string;
  hidden: boolean;
  pwls?: any;
  link_flair_css_class?: any;
  downs: number;
  thumbnail_height: number;
  top_awarded_type?: any;
  hide_score: boolean;
  name: string;
  quarantine: boolean;
  link_flair_text_color: string;
  upvote_ratio: number;
  author_flair_background_color?: any;
  subreddit_type: string;
  ups: number;
  total_awards_received: number;
  media_embed: null;
  thumbnail_width: number;
  author_flair_template_id?: any;
  is_original_content: boolean;
  user_reports: any[];
  secure_media: SecureMedia;
  is_reddit_media_domain: boolean;
  is_meta: boolean;
  category?: any;
  secure_media_embed: null;
  link_flair_text?: any;
  can_mod_post: boolean;
  score: number;
  approved_by?: any;
  is_created_from_ads_ui: boolean;
  author_premium: boolean;
  thumbnail: string;
  edited: boolean;
  author_flair_css_class?: any;
  author_flair_richtext: any[];
  gildings: null;
  post_hint: string;
  content_categories?: any;
  is_self: boolean;
  mod_note?: any;
  created: number;
  link_flair_type: string;
  wls?: any;
  removed_by_category?: any;
  banned_by?: any;
  author_flair_type: string;
  domain: string;
  allow_live_comments: boolean;
  selftext_html?: any;
  likes?: any;
  suggested_sort?: any;
  banned_at_utc?: any;
  url_overridden_by_dest: string;
  view_count?: any;
  archived: boolean;
  no_follow: boolean;
  is_crosspostable: boolean;
  pinned: boolean;
  over_18: boolean;
  preview: Preview;
  all_awardings: AllAwarding[];
  awarders: any[];
  media_only: boolean;
  can_gild: boolean;
  spoiler: boolean;
  locked: boolean;
  author_flair_text?: any;
  treatment_tags: any[];
  visited: boolean;
  removed_by?: any;
  num_reports?: any;
  distinguished?: any;
  subreddit_id: string;
  author_is_blocked: boolean;
  mod_reason_by?: any;
  removal_reason?: any;
  link_flair_background_color: string;
  id: string;
  is_robot_indexable: boolean;
  report_reasons?: any;
  author: string;
  discussion_type?: any;
  num_comments: number;
  send_replies: boolean;
  whitelist_status?: any;
  contest_mode: boolean;
  mod_reports: any[];
  author_patreon_flair: boolean;
  author_flair_text_color?: any;
  permalink: string;
  parent_whitelist_status?: any;
  stickied: boolean;
  url: string;
  subreddit_subscribers: number;
  created_utc: number;
  num_crossposts: number;
  media: Media;
  is_video: boolean;
  crosspost_parent_list: CrosspostParentList[];
  crosspost_parent: string;
};

type Child = {
  kind: string;
  data: PostData;
};

type Data = {
  after: string;
  dist: number;
  modhash: string;
  geo_filter?: any;
  children: Child[];
  before?: any;
};

export type RedditHotPostsResponse = {
  kind: string;
  data: Data;
};

export type RedditAboutResponse = {
  kind: string;
  data: {
    user_flair_background_color?: any;
    submit_text_html?: any;
    restrict_posting: boolean;
    user_is_banned: boolean;
    free_form_reports: boolean;
    wiki_enabled?: any;
    user_is_muted: boolean;
    user_can_flair_in_sr: boolean;
    display_name: string;
    header_img?: any;
    title: string;
    original_content_tag_enabled: boolean;
    allow_galleries: boolean;
    icon_size?: any;
    primary_color: string;
    active_user_count: number;
    icon_img: string;
    display_name_prefixed: string;
    accounts_active: number;
    public_traffic: boolean;
    subscribers: number;
    user_flair_richtext: any[];
    videostream_links_count: number;
    name: string;
    quarantine: boolean;
    hide_ads: boolean;
    prediction_leaderboard_entry_type: string;
    emojis_enabled: boolean;
    advertiser_category: string;
    public_description: string;
    comment_score_hide_mins: number;
    allow_predictions: boolean;
    user_has_favorited: boolean;
    user_flair_template_id?: any;
    community_icon: string;
    banner_background_image: string;
    header_title: string;
    community_reviewed: boolean;
    submit_text: string;
    description_html: string;
    spoilers_enabled: boolean;
    allow_talks: boolean;
    header_size?: any;
    user_flair_position: string;
    all_original_content: boolean;
    has_menu_widget: boolean;
    is_enrolled_in_new_modmail?: any;
    key_color: string;
    can_assign_user_flair: boolean;
    created: number;
    wls?: any;
    show_media_preview: boolean;
    submission_type: string;
    user_is_subscriber: boolean;
    disable_contributor_requests: boolean;
    allow_videogifs: boolean;
    should_archive_posts: boolean;
    user_flair_type: string;
    allow_polls: boolean;
    collapse_deleted_comments: boolean;
    emojis_custom_size?: any;
    public_description_html: string;
    allow_videos: boolean;
    is_crosspostable_subreddit: boolean;
    notification_level?: any;
    can_assign_link_flair: boolean;
    accounts_active_is_fuzzed: boolean;
    allow_prediction_contributors: boolean;
    submit_text_label: string;
    link_flair_position: string;
    user_sr_flair_enabled: boolean;
    user_flair_enabled_in_sr: boolean;
    allow_discovery: boolean;
    accept_followers: boolean;
    user_sr_theme_enabled: boolean;
    link_flair_enabled: boolean;
    subreddit_type: string;
    suggested_comment_sort?: any;
    banner_img: string;
    user_flair_text?: any;
    banner_background_color: string;
    show_media: boolean;
    id: string;
    user_is_moderator: boolean;
    over18: boolean;
    description: string;
    submit_link_label: string;
    user_flair_text_color?: any;
    restrict_commenting: boolean;
    user_flair_css_class?: any;
    allow_images: boolean;
    lang: string;
    whitelist_status?: any;
    url: string;
    created_utc: number;
    banner_size?: any;
    mobile_banner_image: string;
    user_is_contributor: boolean;
    allow_predictions_tournament: boolean;
  };
};

export type MemeImage = {
  url: string;
};

export type MemeVideo = {
  videoUrl: string;
  audioUrl: string;
  thumbnailUrl?: string;
};

export type Meme = {
  image?: MemeImage;
  video?: MemeVideo;
  title?: string;
  author?: string;
  subreddit?: string;
};
